name: Deploy fib-app
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t feroza/fib-app-client-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true feroza/fib-app-client-test npm test

      - run: docker build -t feroza/fib-app-client ./client
      - run: docker build -t feroza/fib-app-server ./server
      - run: docker build -t feroza/fib-app-worker ./worker
      - run: docker build -t feroza/fib-app-nginx ./nginx

      - run: docker push feroza/fib-app-client
      - run: docker push feroza/fib-app-server
      - run: docker push feroza/fib-app-worker
      - run: docker push feroza/fib-app-nginx

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fib-app
          environment_name: Fib-app-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-062992551369
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
